[workspace]
members = [ "dionysus", "midas"]
resolver = "2"

[workspace.package]
version = "0.9.0"
authors = ["Filipe Nascimento <filipedecn@gmail.com>"]
edition = "2021"
documentation = ""

[workspace.dependencies]
